### ISSUE TITLE
https://www.chase.com does not work

### ISSUE THREAD

**Issue by daguej** [RoelVB/ChromeKeePass#109]
Autofill recently stopped working on [Chase](https://www.chase.com).  ChromeKeePass' icon does not show up in the login fields, and re-detect fields does not help.

I haven't dug deeply, but I wouldn't be surprised if they're doing something dumb in JS to intentionally break autofill.

**Comment by RoelVB** [comment]
They put the input fields in a so called "Shadow DOM", because this the fields are in a separate from the rest of the page.
Theoretically we could still detect those fields, but that would a quite a lot of complexity for an edge case. So it's not something that I will be adding any time soon.

As a workaround, you can right click the field and pick `ChromeKeePass` > `Fill user`/`Fill pass`
