### ISSUE TITLE
Here's a new batch of sites with problems 

### ISSUE THREAD

**Issue by f1h0** [RoelVB/ChromeKeePass#16]
https://cp.beget.com
when I want to choose my account, it has a strange behavior.
the plugin works with other websites.

https://passport.yandex.com
on this site the selected entry via the plugin does not work

https://www.nic.ru/en/auth/login/
when I select an account and click login, the password is erased.

https://account.elama.global/
the ChromeKeePass plugin does not work on this site at all.

**Comment by f1h0** [comment]
I often use these sites with a lot of clients I help out with.

**Comment by RoelVB** [comment]
Thanks.

**Beget.com**
It looks like this doesn't work when single clicking credentials. But when I double click or use enter it seems to work. Can you confirm this is the same for you?

**Yandex**
I don't know how to solve this. You have to press "Log in" twice. Before the first login the password field is there, but hidden. But is looks like after you press "log in" they create a new password field (which of course is then empty)
As a workaround when you get at the empty password field you could right click and choose "Redetect fields" under "ChromeKeePass". Then you should be able to enter the password.

**NIC**
Seems to work fine for me

**eLama**
Same method as for Yandex. Right click and choose redetect fields.

I'm thinking about a beter way to redetecting fields, but I'm not sure how I'm going to do that yet.

**Comment by f1h0** [comment]
that's what I noticed.
**Beget.com**
if you access the site via the home page https://beget.com.
I don't have a login field.
![image](https://user-images.githubusercontent.com/1436880/79313645-507ca280-7f09-11ea-8994-209ea2a7a5f3.png)


**Yandex**
here's what I do. 
![l6KiH](https://user-images.githubusercontent.com/1436880/79315545-c2ee8200-7f0b-11ea-8ec7-2fa7040e462e.gif)

your references tried, they didn't work.

**Comment by BlaM** [comment]
On https://www.namecheap.com/ when I click somewhere on the page the "ChromeKeePass" layer appears in the top left corner.

**Comment by RoelVB** [comment]
@BlaM Could you maybe post a screenshot? I don't have any issues there.

**Comment by BlaM** [comment]
Interesting - and yes, you may be right. This is what happens for me:

![namecheap](https://user-images.githubusercontent.com/176011/89924369-370f0d00-dc02-11ea-8d40-090a09128988.gif)

*BUT:* If I do the same in incognito mode, nothing happens - so that might be an compatibility issue with another addon I use. I'll try to figure out which one it is and get back to you. Until then feel free to ignore my previous comment ;)

**Comment by RoelVB** [comment]
@BlaM 
Could you try this:
1. When on the site
1. Open the DevTools (F12)
2. Goto the console and execute the command `$('input[type="password"]')`
What's the result?

**Comment by BlaM** [comment]
It returns the correct (single) password input field, but that `<input>` lies inside a hidden `<div>`.

Quick sidenote: namecheap does not use jQuery, so "$" is the version built in in Chrome - which will always return one element max. I injected jQuery into the page for this test, though.

`jQuery('input[type="password"]')` returns one password field, `jQuery('input[type="password"]:visible')` returns *no* results.

**Comment by RoelVB** [comment]
@BlaM Thank you, this is useful information.

It pointed me to the issue. It turns out I do check if a username field is visible:
https://github.com/RoelVB/ChromeKeePass/blob/master/src/classes/PageControl.ts#L39-L41
But I don't check this for password fields. I'll try to find some time this weekend to change this.

It still doesn't make sense to me that the dropdown shows up for you, but I'm almost certain checking the visibility of the password field will fix this.

**Comment by RoelVB** [comment]
@BlaM Didn't make it this weekend, but did it today.
I will take some time before the fix is published (the update needs to be validated by Google).

**Comment by BlaM** [comment]
Let's see and wait how it works with those multi-step login forms like the one @f1h0 posted from Yandex. 

Those might become a problem and I guess they will be more and more common for bigger sites that use federation with big companies (step 1 recognizes if you are coming from company XY and will then send you to the company log in page to actually sign in with your work-login). But to be honest: Those are clumpsy with other password managers as well.
