### ISSUE TITLE
Email Login field not detected on ASANA Website

### ISSUE THREAD

**Issue by nGgit11** [RoelVB/ChromeKeePass#78]
On the Email login field the extension is not detected, no autofill detected, even after using "Redetect fields"

https://user-images.githubusercontent.com/101392238/158093546-8a1ca732-fb78-419b-9bc0-7e7802a78f53.mp4

<img width="694" alt="2022-03-14_094026" src="https://user-images.githubusercontent.com/101392238/158093585-78ba9d33-53ad-4e14-a1a3-5072cf27c335.png">

Site with problem: https://app.asana.com/-/login
ChromeKeePass version: 1.4.4
KeePass version: 2.50
Chrome Version: 98.0.4758.82 

<img width="621" alt="asana-1" src="https://user-images.githubusercontent.com/101392238/158092778-aaebbc06-b16d-4e7c-a422-ee727025dc00.png">

On the password field it works, aside from the "eye password peaking" icon overtaking the chromekeepass extension, but if you click the empty field the extension detected the password.
<img width="398" alt="asana-3" src="https://user-images.githubusercontent.com/101392238/158093506-c3b8c806-2b85-4f26-8a07-87c3d9007ba8.png">

**Comment by RoelVB** [comment]
Thank you for the very clear report. A video is always very helpful.

The problem here is that the initial login page doesn't contain a password field, which mains CKP doesn't see it as a login page.
They seem to have changed the login page, because according to #49 it has worked.
On most website that don't immediately show the password field, it's just hidden. Therefore CKP will detect it and work just fine.

In this case it's a little difficult. Because for CKP this is just some random input field. I don't want to add CKP to every input field.

I do have some plans to improve this in the future BTW.
